export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FAIL_RETRIEVING_DATA = "FAIL_RETRIEVING_DATA";
export const SET_OFFERS = "SET_OFFERS";
export const SET_CURRENT_OFFER = "SET_CURRENT_OFFER";
export const SET_MARKS = "SET_MARKS";
export const SET_MODELS = "SET_MODELS";
export const SET_GENERATIONS = "SET_GENERATIONS";
export const SET_MAIN_IMAGE = "SET_MAIN_IMAGE";
export const SET_COVER_IMAGE = "SET_COVER_IMAGE";
export const SET_GALLERY = "SET_GALLERY";
export const UPDATE_GALLERY = "UPDATE_GALLERY";
export const DELETE_FROM_GALLERY = "DELETE_FROM_GALLERY";
export const CLEAR_MODELS = "CLEAR_MODELS";
export const CLEAR_GENERATIONS = "CLEAR_GENERATIONS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FAIL_RETRIEVING_DATA_IN_PROFILE = "FAIL_RETRIEVING_DATA_IN_PROFILE";
export const SET_OFFERS_IN_PROFILE = "SET_OFFERS_IN_PROFILE";
export const SET_FAVOURITES_IN_PROFILE = "SET_FAVOURITES_IN_PROFILE";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";